### ISSUE TITLE
building OPX2.2

### ISSUE THREAD

**Issue by reju85** [open-switch/opx-build#25]
Hi,
We are building OPX2.2
When we run package assemble script it also download all the package from scratch so the build takes lot of time.Is there any way to cache so that minimize the build time?

**Comment by theucke** [comment]
You'll have to be more specific. What do you mean by "package assemble script"? We have a package build script (`opx_build`) and an installer assemble script (`opx_rel_pkgasm.py`), but no package assemble script.

**Comment by theucke** [comment]
OPX packages are cached in the `pool/` directory of your workspace. Debian packages are cached only in the docker container. If the container is removed, those dependencies need to be downloaded again.

`opx_run` removes the container after running. You could start the container without `--rm` and just run `opx_build` inside of the container to keep the container alive.
