### ISSUE TITLE
openflow

### ISSUE THREAD

**Issue by junhengdi** [open-switch/opx-build#30]
Hi,I am finding a way to make traditional switch support openflow and so I am building opx. But I want to know whether the opx can support openflow. I can not find the feature on opx about openflow.

**Comment by junhengdi** [comment]
Now,I can build the unstable opx according to the guide.But when I want to build the release version such as 2.2.0/2.2.1/2.3.0 , there are some error.  When I use the assemble installer script ,it appears. just like this:

Sysroot is in /tmp/tmpjtgsvX
Using copy:/mnt stable main
Using http://deb.openswitch.net/jessie stable main opx opx-non-free
Using http://httpredir.debian.org/debian jessie main
Using http://httpredir.debian.org/debian jessie-updates main
Using http://httpredir.debian.org/debian jessie-backports main
Get:1 copy:/mnt/ stable/main opx-platform-config-dell-s5148f all 1.4.9 [16.8 kB]                                                                                                                                                            
Get:2 copy:/mnt/ stable/main opx-dell-s5148f all 1.4.9 [2740 B]                                                                                                                                                                             
Get:3 http://deb.openswitch.net/jessie/ stable/opx-non-free libopx-sai-xpliant1 amd64 1.2.5 [3376 kB] 
Err http://deb.openswitch.net/jessie/ stable/opx-non-free opx-cavium-modules amd64 1.0.0   
 Connection failed [IP: 52.27.65.128 80]                                                                                                                                                                                                   
Fetched 3396 kB in 6s (0 B/s)                                                                                                                                                                                                               
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1395, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1345, in main
    rel_plan.add_packages()
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 946, in add_packages
    packer.fetch(names=deb_package_list)
  File "/opt/opx-build/scripts/opx_get_packages.py", line 502, in fetch
    self._cache.fetch_archives()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 355, in fetch_archives
    apt_pkg.PackageManager(self._depcache))
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 330, in _fetch_archives
    return self._run_fetcher(fetcher)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 309, in _run_fetcher
    raise FetchFailedException(err_msg)
opx_get_packages.OpxPackagesError: Fetch failed
Failed to fetch http://deb.openswitch.net/jessie/pool/opx-non-free/o/opx-cavium-modules/opx-cavium-modules_1.0.0_amd64.deb Connection failed [IP: 52.27.65.128 80]

**Comment by junhengdi** [comment]
commond like this :
OPX_RELEASE=2.3.0 opx-build/scripts/opx_run opx_build all
opx-build/scripts/opx_run opx_rel_pkgasm.py --dist stable \
  -b opx-onie-installer/release_bp/OPX_dell_base.xml

**Comment by jeff-yin** [comment]
@theucke can you help out @junhengdi with the build issue he indicated above?

**Comment by theucke** [comment]
@junhengdi That looks like a network issue. I can access the file in the error without issue. Can you try running the command again?

**Comment by junhengdi** [comment]
Thanks a lot. I  tried many times and finally I got PKGS_OPX-stable.9999-installer-x86_64.bin.It takes lots of time to download all of the packet. By the way, whether the latest version of opx can support openflow?

**Comment by theucke** [comment]
I'm not sure on openflow support. You'll get the fastest answer to that question in our [RocketChat](https://chat.openswitch.net/channel/general).
