### ISSUE TITLE
RFE: Include Web Management Console for OPX

### ISSUE THREAD

**Issue by donnydavis** [open-switch/opx-build#33]
It would be really fantastic to have a web console for OPX OOB. 
Including https://cockpit-project.org in the build would be an easy way to get this feature

**Comment by donnydavis** [comment]
Its seems to work without much in the way of modification

![screenshot from 2018-05-28 12-15-53](https://user-images.githubusercontent.com/15927081/40622745-06e25978-6271-11e8-9ce1-62d21c5c77a8.png)

**Comment by jeff-yin** [comment]
Hi @donnydavis, that looks cool. We've also tried this out with [webmin](http://www.webmin.com/) before and it also worked pretty well. Have you tried webmin? If so, how do you think it compares to cockpit?

**Comment by jeff-yin** [comment]
Closing. We won't include this in the build to keep the installer size down, but users are always welcome to install their own preferred web console of choice, whether it's this or webmin or anything else.
