### ISSUE TITLE
Does not build with latest

### ISSUE THREAD

**Issue by kot-begemot-uk** [open-switch/opx-build#37]
When building opx-base-model build fails with

configure: WARNING: unrecognized options: --disable-maintainer-mode
   dh_auto_build
	make -j1
make[1]: Entering directory '/build/opx-base-model-3.112.0'
YANG_PATH=/build/opx-base-model-3.112.0/common/yumaworks:/build/opx-base-model-3.112.0/rfc:/build/opx-base-model-3.112.0/common/dell:/build/opx-base-model-3.112.0/yang-models /usr/lib/opx/ar_parse_yang.sh yumaworks-extensions.yang ./opx ./opx
Traceback (most recent call last):
  File "/usr/bin/pyang", line 12, in <module>
    from pyang import plugin
  File "/usr/local/lib/python2.7/dist-packages/pyang/plugin.py", line 5, in <module>
    import pkg_resources
ImportError: No module named pkg_resources

pkg_resources if memory serves me right is part of the core python environment. If it fails to find it, this means that the core python environment is not set-up correctly.

**Comment by theucke** [comment]
It doesn't seem like it is anymore in Stretch: https://packages.debian.org/stretch/python-pkg-resources

`python-pkg-resources` needs to be added as a build dependency to `opx-base-model`.

```diff
────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: debian/control
────────────────────────────────────────────────────────────────────────────────────────────────────────
@ control:6 @ Section: net
 Priority: optional
 Maintainer: Dell EMC <ops-dev@lists.openswitch.net>
 Build-Depends:
- debhelper (>=9), dh-autoreconf, libopx-cps-dev (>= 3.6.2), opx-yang-utils-dev (>= 3.6.2), python-lxml
+ debhelper (>=9), dh-autoreconf, libopx-cps-dev (>= 3.6.2), opx-yang-utils-dev (>= 3.6.2), python-lxml, python-pkg-resources
 Standards-Version: 3.9.3
 Vcs-Browser: https://github.com/open-switch/opx-base-model
 Vcs-Git: https://github.com/open-switch/opx-base-model.git
```

Then `opx-base-model` will build. I've opened open-switch/opx-base-model#27 for this.
