### ISSUE TITLE
Can't  build opx-onie-installer

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#40]
```
root@jimmy-VirtualBox:/home/jimmy/opx# opx-build/scripts/opx_run opx_rel_pkgasm.py --dist stable -b opx-onie-installer/release_bp/OPX_dell_base.xml
fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-jessie_amd64.tar.gz ...
tar_in(self, /tmp/tmpT2zxI4, /)
tar_in(['fakeroot', '-i', '/tmp/tmpIanPfw', '-s', '/tmp/tmpIanPfw', 'tar', '-C', '/tmp/tmpVOmQqa/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions'])
update_rootfs(self)
do_chroot(self, /opt/opx-build/scripts/templates/do_apt_upgrade_sh)
do_chroot
['fakechroot', 'fakeroot', '-i', '/tmp/tmpIanPfw', '-s', '/tmp/tmpIanPfw', '/usr/sbin/chroot', '/tmp/tmpVOmQqa', '/do_apt_upgrade_sh']
/usr/sbin/chroot.fakechroot: line 105:    93 Segmentation fault      (core dumped) env -u FAKECHROOT_BASE_ORIG FAKECHROOT_CMD_ORIG= LD_LIBRARY_PATH="$fakechroot_chroot_paths" FAKECHROOT_BASE="$fakechroot_chroot_base" "$fakechroot_chroot_chroot" "${@:1:$(($fakechroot_chroot_n - 1))}" "${fakechroot_chroot_newroot#$FAKECHROOT_BASE_ORIG}" "${@:$(($fakechroot_chroot_n + 1))}"
Command '['fakechroot', 'fakeroot', '-i', '/tmp/tmpIanPfw', '-s', '/tmp/tmpIanPfw', '/usr/sbin/chroot', '/tmp/tmpVOmQqa', '/do_apt_upgrade_sh']' returned non-zero exit status 139
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1350, in main
    rel_plan.update_rootfs()
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 911, in update_rootfs
    self._root_obj.do_chroot(script_nm)
  File "/opt/opx-build/scripts/opx_rootfs.py", line 350, in do_chroot
    raise OpxrootfsError("Can't run script")
opx_rootfs.OpxrootfsError: Can't run script
root@jimmy-VirtualBox:/home/jimmy/opx# 
```

Any suggestion is appreciated~

**Comment by jimmymagemtek** [comment]
Without using onie installer, can I just install all the *.deb in each folder under "pool", one by one, to the target platform's rootfs ?

Any suggestion is appreciated.

**Comment by theucke** [comment]
Fakechroot segfaults usually come from some libc mismatch. Are you trying to build a Jessie or Stretch installer?

- If stretch, change the blueprint from `opx-onie-installer/release_bp/OPX_dell_base.xml` to `opx-onie-installer/release_bp/OPX_dell_base_stretch.xml`
- If jessie, build using a Jessie-based Docker image with `VERSION=jessie DIST=jessie opx-build/scripts/opx_run opx_rel_pkgasm.py --dist stable -b opx-onie-installer/release_bp/OPX_dell_base.xml`

**Comment by jimmymagemtek** [comment]
Thanks.

root@debian:/home/jimmy/opx# opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml
fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-stretch_amd64.tar.gz ...
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1349, in main
    rel_plan = OpxRelPackageAssembler(rel_blueprint)
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 743, in __init__
    rootfs_sha1=self._blueprint.rootfs['sha1'])
  File "/opt/opx-build/scripts/opx_rootfs.py", line 140, in __init__
    for chunk in resp.iter_content(chunk_size):
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 706, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
root@debian:/home/jimmy/opx# 


There  seems to be connection issue this time.
Any suggestion is appreciated.

**Comment by theucke** [comment]
Looks like a network issue on your end. Can you try manually downloading the tarball in your log?

> http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-stretch_amd64.tar.gz

**Comment by jimmymagemtek** [comment]
Thanks. You are right.
I re-try the command. and I could download tar ball this time, but still got another error:

root@debian:/home/jimmy/opx# opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml
fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-stretch_amd64.tar.gz ...
tar_in(self, /tmp/tmp5z8ZXH, /)
tar_in(['fakeroot', '-i', '/tmp/tmpvCKwU3', '-s', '/tmp/tmpvCKwU3', 'tar', '-C', '/tmp/tmpupjPK6/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions'])
tar: ./usr/share/misc: Directory renamed before its status could be extracted
tar: ./usr/share/man/man2: Directory renamed before its status could be extracted
tar: ./usr/share/man/man3: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv: Directory renamed before its status could be extracted
tar: ./usr/share/man/it/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/it: Directory renamed before its status could be extracted
tar: ./usr/share/man/man7: Directory renamed before its status could be extracted
tar: ./usr/share/man/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl: Directory renamed before its status could be extracted
tar: ./usr/share/man/man8: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr: Directory renamed before its status could be extracted
tar: ./usr/share/man/es/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/es: Directory renamed before its status could be extracted
tar: ./usr/share/man/man5: Directory renamed before its status could be extracted
tar: ./usr/share/man: Directory renamed before its status could be extracted
tar: ./usr/share/doc/build-essential: Directory renamed before its status could be extracted
tar: ./usr/share/doc/cpp: Directory renamed before its status could be extracted
tar: ./usr/share/doc/python2.7: Directory renamed before its status could be extracted
tar: ./usr/share/doc: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/timers.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sysinit.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sockets.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/rescue.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/multi-user.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/local-fs.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/graphical.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/getty.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system: Directory renamed before its status could be extracted
tar: ./lib/systemd: Directory renamed before its status could be extracted
tar: ./lib: Directory renamed before its status could be extracted
tar: ./var/spool: Directory renamed before its status could be extracted
tar: ./var: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
Command '['fakeroot', '-i', '/tmp/tmpvCKwU3', '-s', '/tmp/tmpvCKwU3', 'tar', '-C', '/tmp/tmpupjPK6/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1349, in main
    rel_plan = OpxRelPackageAssembler(rel_blueprint)
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 743, in __init__
    rootfs_sha1=self._blueprint.rootfs['sha1'])
  File "/opt/opx-build/scripts/opx_rootfs.py", line 159, in __init__
    self.tar_in(fd_.name)
  File "/opt/opx-build/scripts/opx_rootfs.py", line 421, in tar_in
    raise OpxrootfsError("Can't extract tarball")
opx_rootfs.OpxrootfsError: Can't extract tarball
root@debian:/home/jimmy/opx# 

I am using root account.

And I tried to download the tar ball by using "wget" & extracted it manually. The result is OK.

Any suggestion is  appreciated.

**Comment by theucke** [comment]
Can you try as a regular user and not root?

**Comment by jimmymagemtek** [comment]
A regular user got permission denial as below,

jimmy@debian:~/opx$ opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/create?name=jimmy_opx_20239: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.


And I use "sudo" still got the same error as using root,

jimmy@debian:~/opx$ sudo opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml
[sudo] password for jimmy: 
fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-stretch_amd64.tar.gz ...
tar_in(self, /tmp/tmpfmmanc, /)
tar_in(['fakeroot', '-i', '/tmp/tmp62FSdd', '-s', '/tmp/tmp62FSdd', 'tar', '-C', '/tmp/tmp1G0SoK/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions'])
tar: ./usr/share/man/man3: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv: Directory renamed before its status could be extracted
tar: ./usr/share/man/it/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/it: Directory renamed before its status could be extracted
tar: ./usr/share/man/man7: Directory renamed before its status could be extracted
tar: ./usr/share/man/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl: Directory renamed before its status could be extracted
tar: ./usr/share/man/man8: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr: Directory renamed before its status could be extracted
tar: ./usr/share/man/es/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/es: Directory renamed before its status could be extracted
tar: ./usr/share/man/man5: Directory renamed before its status could be extracted
tar: ./usr/share/doc/build-essential: Directory renamed before its status could be extracted
tar: ./usr/share/doc/cpp: Directory renamed before its status could be extracted
tar: ./usr/share/doc/python2.7: Directory renamed before its status could be extracted
tar: ./usr/share/doc: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/timers.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sysinit.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sockets.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/rescue.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/multi-user.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/local-fs.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/graphical.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/getty.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system: Directory renamed before its status could be extracted
tar: ./lib/systemd: Directory renamed before its status could be extracted
tar: ./lib: Directory renamed before its status could be extracted
tar: ./var/spool: Directory renamed before its status could be extracted
tar: ./var: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
Command '['fakeroot', '-i', '/tmp/tmp62FSdd', '-s', '/tmp/tmp62FSdd', 'tar', '-C', '/tmp/tmp1G0SoK/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1349, in main
    rel_plan = OpxRelPackageAssembler(rel_blueprint)
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 743, in __init__
    rootfs_sha1=self._blueprint.rootfs['sha1'])
  File "/opt/opx-build/scripts/opx_rootfs.py", line 159, in __init__
    self.tar_in(fd_.name)
  File "/opt/opx-build/scripts/opx_rootfs.py", line 421, in tar_in
    raise OpxrootfsError("Can't extract tarball")
opx_rootfs.OpxrootfsError: Can't extract tarball

**Comment by theucke** [comment]
The first error comes from not setting up Docker for your user: https://docs.docker.com/install/linux/linux-postinstall/

Once you fix that, try it again without sudo.

**Comment by jimmymagemtek** [comment]
I set up docker & tried it without sudo, and I got the same error,

jimmy@debian:~/opx$ opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml
fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-stretch_amd64.tar.gz ...
tar_in(self, /tmp/tmpKHLpsx, /)
tar_in(['fakeroot', '-i', '/tmp/tmphIavB7', '-s', '/tmp/tmphIavB7', 'tar', '-C', '/tmp/tmp5FoNCq/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions'])
tar: ./usr/share/misc: Directory renamed before its status could be extracted
tar: ./usr/share/man/man2: Directory renamed before its status could be extracted
tar: ./usr/share/man/man3: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv: Directory renamed before its status could be extracted
tar: ./usr/share/man/it/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/it: Directory renamed before its status could be extracted
tar: ./usr/share/man/man7: Directory renamed before its status could be extracted
tar: ./usr/share/man/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl: Directory renamed before its status could be extracted
tar: ./usr/share/man/man8: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr: Directory renamed before its status could be extracted
tar: ./usr/share/man/es/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/es: Directory renamed before its status could be extracted
tar: ./usr/share/man/man5: Directory renamed before its status could be extracted
tar: ./usr/share/man: Directory renamed before its status could be extracted
tar: ./usr/share/doc/build-essential: Directory renamed before its status could be extracted
tar: ./usr/share/doc/cpp: Directory renamed before its status could be extracted
tar: ./usr/share/doc/python2.7: Directory renamed before its status could be extracted
tar: ./usr/share/doc: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/timers.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sysinit.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sockets.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/rescue.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/multi-user.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/local-fs.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/graphical.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/getty.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system: Directory renamed before its status could be extracted
tar: ./lib/systemd: Directory renamed before its status could be extracted
tar: ./lib: Directory renamed before its status could be extracted
tar: ./var/spool: Directory renamed before its status could be extracted
tar: ./var: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
Command '['fakeroot', '-i', '/tmp/tmphIavB7', '-s', '/tmp/tmphIavB7', 'tar', '-C', '/tmp/tmp5FoNCq/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1349, in main
    rel_plan = OpxRelPackageAssembler(rel_blueprint)
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 743, in __init__
    rootfs_sha1=self._blueprint.rootfs['sha1'])
  File "/opt/opx-build/scripts/opx_rootfs.py", line 159, in __init__
    self.tar_in(fd_.name)
  File "/opt/opx-build/scripts/opx_rootfs.py", line 421, in tar_in
    raise OpxrootfsError("Can't extract tarball")
opx_rootfs.OpxrootfsError: Can't extract tarball
jimmy@debian:~/opx$

**Comment by jimmymagemtek** [comment]
I set up docker for my user & tried it without sudo, and I got the same issue with root's,

jimmy@debian:~/opx$ opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml
fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-stretch_amd64.tar.gz ...
tar_in(self, /tmp/tmpKHLpsx, /)
tar_in(['fakeroot', '-i', '/tmp/tmphIavB7', '-s', '/tmp/tmphIavB7', 'tar', '-C', '/tmp/tmp5FoNCq/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions'])
tar: ./usr/share/misc: Directory renamed before its status could be extracted
tar: ./usr/share/man/man2: Directory renamed before its status could be extracted
tar: ./usr/share/man/man3: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv: Directory renamed before its status could be extracted
tar: ./usr/share/man/it/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/it: Directory renamed before its status could be extracted
tar: ./usr/share/man/man7: Directory renamed before its status could be extracted
tar: ./usr/share/man/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl: Directory renamed before its status could be extracted
tar: ./usr/share/man/man8: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr: Directory renamed before its status could be extracted
tar: ./usr/share/man/es/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/es: Directory renamed before its status could be extracted
tar: ./usr/share/man/man5: Directory renamed before its status could be extracted
tar: ./usr/share/man: Directory renamed before its status could be extracted
tar: ./usr/share/doc/build-essential: Directory renamed before its status could be extracted
tar: ./usr/share/doc/cpp: Directory renamed before its status could be extracted
tar: ./usr/share/doc/python2.7: Directory renamed before its status could be extracted
tar: ./usr/share/doc: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/timers.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sysinit.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sockets.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/rescue.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/multi-user.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/local-fs.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/graphical.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/getty.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system: Directory renamed before its status could be extracted
tar: ./lib/systemd: Directory renamed before its status could be extracted
tar: ./lib: Directory renamed before its status could be extracted
tar: ./var/spool: Directory renamed before its status could be extracted
tar: ./var: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
Command '['fakeroot', '-i', '/tmp/tmphIavB7', '-s', '/tmp/tmphIavB7', 'tar', '-C', '/tmp/tmp5FoNCq/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1349, in main
    rel_plan = OpxRelPackageAssembler(rel_blueprint)
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 743, in __init__
    rootfs_sha1=self._blueprint.rootfs['sha1'])
  File "/opt/opx-build/scripts/opx_rootfs.py", line 159, in __init__
    self.tar_in(fd_.name)
  File "/opt/opx-build/scripts/opx_rootfs.py", line 421, in tar_in
    raise OpxrootfsError("Can't extract tarball")
opx_rootfs.OpxrootfsError: Can't extract tarball
jimmy@debian:~/opx$

**Comment by jimmymagemtek** [comment]
I set up docker for my user & tried it without sudo, and I got the same issue as using root,


jimmy@debian:~/opx$ opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml
fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-stretch_amd64.tar.gz ...
tar_in(self, /tmp/tmpKHLpsx, /)
tar_in(['fakeroot', '-i', '/tmp/tmphIavB7', '-s', '/tmp/tmphIavB7', 'tar', '-C', '/tmp/tmp5FoNCq/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions'])
tar: ./usr/share/misc: Directory renamed before its status could be extracted
tar: ./usr/share/man/man2: Directory renamed before its status could be extracted
tar: ./usr/share/man/man3: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/sv: Directory renamed before its status could be extracted
tar: ./usr/share/man/it/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/it: Directory renamed before its status could be extracted
tar: ./usr/share/man/man7: Directory renamed before its status could be extracted
tar: ./usr/share/man/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ru: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/pl: Directory renamed before its status could be extracted
tar: ./usr/share/man/man8: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/ja: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/fr: Directory renamed before its status could be extracted
tar: ./usr/share/man/es/man1: Directory renamed before its status could be extracted
tar: ./usr/share/man/es: Directory renamed before its status could be extracted
tar: ./usr/share/man/man5: Directory renamed before its status could be extracted
tar: ./usr/share/man: Directory renamed before its status could be extracted
tar: ./usr/share/doc/build-essential: Directory renamed before its status could be extracted
tar: ./usr/share/doc/cpp: Directory renamed before its status could be extracted
tar: ./usr/share/doc/python2.7: Directory renamed before its status could be extracted
tar: ./usr/share/doc: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/timers.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sysinit.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/sockets.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/rescue.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/multi-user.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/local-fs.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/graphical.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system/getty.target.wants: Directory renamed before its status could be extracted
tar: ./lib/systemd/system: Directory renamed before its status could be extracted
tar: ./lib/systemd: Directory renamed before its status could be extracted
tar: ./lib: Directory renamed before its status could be extracted
tar: ./var/spool: Directory renamed before its status could be extracted
tar: ./var: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
Command '['fakeroot', '-i', '/tmp/tmphIavB7', '-s', '/tmp/tmphIavB7', 'tar', '-C', '/tmp/tmp5FoNCq/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1349, in main
    rel_plan = OpxRelPackageAssembler(rel_blueprint)
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 743, in __init__
    rootfs_sha1=self._blueprint.rootfs['sha1'])
  File "/opt/opx-build/scripts/opx_rootfs.py", line 159, in __init__
    self.tar_in(fd_.name)
  File "/opt/opx-build/scripts/opx_rootfs.py", line 421, in tar_in
    raise OpxrootfsError("Can't extract tarball")
opx_rootfs.OpxrootfsError: Can't extract tarball
jimmy@debian:~/opx$

**Comment by jimmymagemtek** [comment]
18.06.0-ce

**Comment by jimmymagemtek** [comment]
I re-built it using normal user priviledge, instead of root. And it passes.
Thanks for helping~

**Comment by jeff-yin** [comment]
Awesome!
