### ISSUE TITLE
mkdir: cannot create directory 'pool': Permission denied

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#41]
[root@localhost opx]# opx-build/scripts/opx_run opx_build all
INFO[0021] POST /v1.20/containers/create?name=jimmy_opx_2554 
INFO[0021] POST /v1.20/containers/78946e23450efddab7813ca0cfad85a84bc1dddf20e1bf0b89a86d7dfd04b8db/attach?stderr=1&stdin=1&stdout=1&stream=1 
INFO[0021] POST /v1.20/containers/78946e23450efddab7813ca0cfad85a84bc1dddf20e1bf0b89a86d7dfd04b8db/start 
INFO[0021] POST /v1.20/containers/78946e23450efddab7813ca0cfad85a84bc1dddf20e1bf0b89a86d7dfd04b8db/resize?h=24&w=80 
mkdir: cannot create directory 'pool': Permission denied
INFO[0022] POST /v1.20/containers/78946e23450efddab7813ca0cfad85a84bc1dddf20e1bf0b89a86d7dfd04b8db/wait 
INFO[0022] GET /v1.20/containers/78946e23450efddab7813ca0cfad85a84bc1dddf20e1bf0b89a86d7dfd04b8db/json 
INFO[0022] DELETE /v1.20/containers/78946e23450efddab7813ca0cfad85a84bc1dddf20e1bf0b89a86d7dfd04b8db?v=1 
[root@localhost opx]# opx-build/scripts/opx_run opx_build all
mkdir: cannot create directory 'pool': Permission denied
[root@localhost opx]# 

I am using Fedora 21 with root, since I need to enable opx on Fedora.
And when building, the opx demands running "docker daemon".

Any suggestion is appreciated.

**Comment by theucke** [comment]
I'm unable to reproduce this error, unless I'm root and trying to write to a NFS volume with `root_squash` turned on. Does this sound like your environment? We avoid this by not running as root.

**Comment by jimmymagemtek** [comment]
Thanks.
I download & build opx again with normal user privilege, and run docker & build opx with root privilege.
Then it is building properly & the previous error is gone.

But I still don't know why.
