### ISSUE TITLE
building opx without docker

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#42]
The default way of building opx seems to assume it will run under docker.

Can I build a version not for a docker environment ?
Since I can't make docker run properly on old-version Fedora.

Any suggestion is appreciated.

**Comment by theucke** [comment]
Sure, just set up your environment like in the Dockerfile. We use `git-buildpackage` to build our Debian packages. Dependencies come from http://deb.openswitch.net/
