### ISSUE TITLE
opx built for aarch64 (arm 64 bits)

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#43]
I try to build opx on aarch64 (arm 64 bits), and got the following error,

jimmy@alex-VirtualBox:/home/jimmy/opx$ sudo opx-build/scripts/opx_run opx_build all
Unable to find image 'opxhub/build:latest' locally
latest: Pulling from opxhub/build
55cbf04beb70: Pull complete
4dfddf601f24: Pull complete
d9dcd9e1d8c0: Pull complete
0f8185032660: Pull complete
b4864de97746: Pull complete
843e91e5dbe7: Pull complete
b744d1aa0ba9: Pull complete
9979928a4ba2: Pull complete
9990ffc55815: Pull complete
a64d3bf3b91d: Pull complete
f43c755a5d63: Pull complete
9067796dbadc: Pull complete
7104c699d18d: Pull complete
5a7d9dddd225: Pull complete
Digest: sha256:233048435256a24008ec04f48e818f12bb1b1ea66e58bbe4177c6cca18952ba8
Status: Downloaded newer image for opxhub/build:latest
standard_init_linux.go:178: exec user process caused "exec format error"
jimmy@alex-VirtualBox:~/opx$

It seems to the docker images on github are not for aarch64 architecture. 

Any suggestion is appreciated.

**Comment by jimmymagemtek** [comment]
It looks like that my issue is the same with the one below,

https://github.com/ethereum/go-ethereum/issues/3775


Can OPX provide the docker images for aarch64 compliing ?
Any suggestion is appreciated.

**Comment by theucke** [comment]
You are correct. We do not currently provide aarch64 support.
