### ISSUE TITLE
failed to build docker image for arm64v8

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#45]
I install the opx package on arm64 platform (Cavium CN83XX) with ubuntu 16.4

Under the directory "opx-build",  
1)  I modified the Dockerfile's first line 
"FROM debian/stretch" as "FROM arm64v8/debian:stretch".

2) I modified "docker_build.sh" 's arch from "amd64" to "armhf". 

3) I modified the key word "amd64" inside all the script files under the directory "opx-build/scripts" to "arm64"

After running "docker_build.sh", I got the error message as below,
I: Extracting libuuid1...
I: Extracting mount...
I: Extracting util-linux...
I: Extracting liblzma5...
I: Extracting zlib1g...
W: Failure trying to run: chroot /var/cache/pbuilder/base-jessie-armhf.cow dpkgn
W: See /var/cache/pbuilder/base-jessie-armhf.cow/debootstrap/debootstrap.log fos
W: Failure trying to run: chroot /var/cache/pbuilder/base-jessie-armhf.cow mounc
W: See /var/cache/pbuilder/base-jessie-armhf.cow/debootstrap/debootstrap.log fos
E: debootstrap failed
W: Aborting with an error
E: pbuilder create failed
I: forking: rm -rf /var/cache/pbuilder/base-jessie-armhf.cow
f15e78043102df23662d2942de9f253d27c2beda12595ec751e003ffe81e7a51

Any suggestion is appreciated.

**Comment by jeff-yin** [comment]
Unfortunately arm64 isn't currently a supported architecture in OpenSwitch. I'll close the issue for now, but you can open an enhancement request that we can leave as an open issue to address in the future. Or you can re-open and edit this issue, then label it as an "enhancement"
