### ISSUE TITLE
Errors building onie

### ISSUE THREAD

**Issue by evwarner** [open-switch/opx-build#47]
Running Debian 9.5 and have tried several ways.  Have had no issues building the open-switch software, just can't get the Onie installer to compile:

gms@debian:~/openswitch$ opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable -b opx-onie-installer/release_bp/OPX_dell_base.xml
fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-jessie_amd64.tar.gz ...
tar_in(self, /tmp/tmplQ3ilM, /)
tar_in(['fakeroot', '-i', '/tmp/tmpHxQMZH', '-s', '/tmp/tmpHxQMZH', 'tar', '-C', '/tmp/tmpqlO0M4/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions'])
update_rootfs(self)
do_chroot(self, /opt/opx-build/scripts/templates/do_apt_upgrade_sh)
do_chroot
['fakechroot', 'fakeroot', '-i', '/tmp/tmpHxQMZH', '-s', '/tmp/tmpHxQMZH', '/usr/sbin/chroot', '/tmp/tmpqlO0M4', '/do_apt_upgrade_sh']
/usr/sbin/chroot.fakechroot: line 105:    99 Segmentation fault      (core dumped) env -u FAKECHROOT_BASE_ORIG FAKECHROOT_CMD_ORIG= LD_LIBRARY_PATH="$fakechroot_chroot_paths" FAKECHROOT_BASE="$fakechroot_chroot_base" "$fakechroot_chroot_chroot" "${@:1:$(($fakechroot_chroot_n - 1))}" "${fakechroot_chroot_newroot#$FAKECHROOT_BASE_ORIG}" "${@:$(($fakechroot_chroot_n + 1))}"
Command '['fakechroot', 'fakeroot', '-i', '/tmp/tmpHxQMZH', '-s', '/tmp/tmpHxQMZH', '/usr/sbin/chroot', '/tmp/tmpqlO0M4', '/do_apt_upgrade_sh']' returned non-zero exit status 139
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1350, in main
    rel_plan.update_rootfs()
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 911, in update_rootfs
    self._root_obj.do_chroot(script_nm)
  File "/opt/opx-build/scripts/opx_rootfs.py", line 350, in do_chroot
    raise OpxrootfsError("Can't run script")
opx_rootfs.OpxrootfsError: Can't run script

**Comment by theucke** [comment]
Building the Jessie-based installed in a Jessie container may help with this fakechroot segfault. Add the `DIST=jessie VERSION=jessie` variables.

```bash
DIST=jessie VERSION=jessie opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable -b opx-onie-installer/release_bp/OPX_dell_base.xml
```

**Comment by evwarner** [comment]
Did get somewhat farther but bombed out later on.  See below.  Is there a stretch version?

.  .  .
installed_packages(self)
installed_packages
['fakechroot', 'fakeroot', '/usr/sbin/chroot', '/tmp/tmplcVIEq', 'apt', 'list', '--installed']

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

dpkg-scanpackages: info: Wrote 119 entries to output Packages file.
add_packages(self)
Sysroot is in /tmp/tmplcVIEq
Using http://deb.openswitch.net/contrib stable contrib
Using http://httpredir.debian.org/debian jessie main
Using http://httpredir.debian.org/debian jessie-backports main
Using http://httpredir.debian.org/debian jessie-updates main
Get:1 http://deb.openswitch.net/contrib/ stable/contrib frr amd64 3.0.3-1~debian8+1 [1910 kB]
Get:2 http://httpredir.debian.org/debian/ jessie/main libasprintf0c2 amd64 0.19.3-2 [31.3 kB]
Get:3 http://httpredir.debian.org/debian/ jessie/main libbsd0 amd64 0.7.0-2 [67.9 kB]
Get:4 http://httpredir.debian.org/debian/ jessie/main libedit2 amd64 3.1-20140620-2 [85.1 kB]
Get:5 http://httpredir.debian.org/debian/ jessie/main libevent-2.0-5 amd64 2.0.21-stable-2+deb8u1 [152 kB]
Get:6 http://httpredir.debian.org/debian/ jessie/main libpci3 amd64 1:3.2.1-3 [53.9 kB]
Get:7 http://httpredir.debian.org/debian/ jessie/main libwrap0 amd64 7.6.q-25 [58.5 kB]
Get:8 http://httpredir.debian.org/debian/ jessie/main libxml2 amd64 2.9.1+dfsg1-5+deb8u6 [802 kB]
Get:9 http://httpredir.debian.org/debian/ jessie/main libc-ares2 amd64 1.10.0-2+deb8u2 [72.5 kB]
Get:10 http://httpredir.debian.org/debian/ jessie/main iproute all 1:3.16.0-2 [15.5 kB]
Get:11 http://httpredir.debian.org/debian/ jessie/main libdevmapper-event1.02.1 amd64 2:1.02.90-2.2+deb8u1 [35.8 kB]
Get:12 http://httpredir.debian.org/debian/ jessie/main libpng12-0 amd64 1.2.50-2+deb8u3 [173 kB]
Get:13 http://httpredir.debian.org/debian/ jessie/main libfreetype6 amd64 2.5.2-3+deb8u2 [466 kB]
Get:14 http://httpredir.debian.org/debian/ jessie/main ucf all 3.0030 [69.7 kB]
Get:15 http://httpredir.debian.org/debian/ jessie/main fonts-dejavu-core all 2.34-1 [1047 kB]
Get:16 http://httpredir.debian.org/debian/ jessie/main fontconfig-config all 2.11.0-6.3+deb8u1 [274 kB]
Get:17 http://httpredir.debian.org/debian/ jessie/main libfontconfig1 amd64 2.11.0-6.3+deb8u1 [329 kB]
Get:18 http://httpredir.debian.org/debian/ jessie/main libfuse2 amd64 2.9.3-15+deb8u2 [135 kB]
Get:19 http://httpredir.debian.org/debian/ jessie/main libgeoip1 amd64 1.6.2-4 [90.8 kB]
Get:20 http://httpredir.debian.org/debian/ jessie/main libhiredis0.10 amd64 0.11.0-4 [22.0 kB]
Get:21 http://httpredir.debian.org/debian/ jessie/main libjansson4 amd64 2.7-1+deb8u1 [34.1 kB]
Get:22 http://httpredir.debian.org/debian/ jessie/main dmeventd amd64 2:1.02.90-2.2+deb8u1 [50.2 kB]
Get:23 http://httpredir.debian.org/debian/ jessie/main liblvm2cmd2.02 amd64 2.02.111-2.2+deb8u1 [522 kB]
Get:24 http://httpredir.debian.org/debian/ jessie/main libpcap0.8 amd64 1.6.2-2 [133 kB]
Get:25 http://httpredir.debian.org/debian/ jessie/main libreadline5 amd64 5.2+dfsg-2 [151 kB]
Get:26 http://httpredir.debian.org/debian/ jessie/main libsensors4 amd64 1:3.3.5-2 [51.5 kB]
Get:27 http://httpredir.debian.org/debian/ jessie/main libperl5.20 amd64 5.20.2-3+deb8u11 [1362 B]
Get:28 http://httpredir.debian.org/debian/ jessie/main libsnmp-base all 5.7.2.1+dfsg-1+deb8u1 [1543 kB]
Get:29 http://httpredir.debian.org/debian/ jessie/main libsnmp30 amd64 5.7.2.1+dfsg-1+deb8u1+b1 [2156 kB]
Get:30 http://httpredir.debian.org/debian/ jessie/main libxau6 amd64 1:1.0.8-1 [20.7 kB]
Get:31 http://httpredir.debian.org/debian/ jessie/main libxdmcp6 amd64 1:1.1.1-1+b1 [24.9 kB]
Get:32 http://httpredir.debian.org/debian/ jessie/main libxcb1 amd64 1.10-3+b1 [44.4 kB]
Get:33 http://httpredir.debian.org/debian/ jessie/main libx11-data all 2:1.6.2-3+deb8u1 [126 kB]
Get:34 http://httpredir.debian.org/debian/ jessie/main libx11-6 amd64 2:1.6.2-3+deb8u1 [728 kB]
Get:35 http://httpredir.debian.org/debian/ jessie/main libxrender1 amd64 1:0.9.8-1+b1 [31.4 kB]
Get:36 http://httpredir.debian.org/debian/ jessie/main libxft2 amd64 2.3.2-1 [55.4 kB]
Get:37 http://httpredir.debian.org/debian/ jessie/main gettext-base amd64 0.19.3-2 [121 kB]
Get:38 http://httpredir.debian.org/debian/ jessie/main libisc95 amd64 1:9.9.5.dfsg-9+deb8u15 [169 kB]
Get:39 http://httpredir.debian.org/debian/ jessie/main libdns100 amd64 1:9.9.5.dfsg-9+deb8u15 [682 kB]
Get:40 http://httpredir.debian.org/debian/ jessie/main libisccc90 amd64 1:9.9.5.dfsg-9+deb8u15 [37.3 kB]
Get:41 http://httpredir.debian.org/debian/ jessie/main libisccfg90 amd64 1:9.9.5.dfsg-9+deb8u15 [57.9 kB]
Get:42 http://httpredir.debian.org/debian/ jessie/main libbind9-90 amd64 1:9.9.5.dfsg-9+deb8u15 [44.1 kB]
Get:43 http://httpredir.debian.org/debian/ jessie/main liblwres90 amd64 1:9.9.5.dfsg-9+deb8u15 [53.7 kB]
Get:44 http://httpredir.debian.org/debian/ jessie/main openssh-client amd64 1:6.7p1-5+deb8u4 [693 kB]
Get:45 http://httpredir.debian.org/debian/ jessie/main bind9utils amd64 1:9.9.5.dfsg-9+deb8u15 [168 kB]
Get:46 http://httpredir.debian.org/debian/ jessie/main bind9 amd64 1:9.9.5.dfsg-9+deb8u15 [316 kB]
Get:47 http://httpredir.debian.org/debian/ jessie/main grub-common amd64 2.02~beta2-22+deb8u1 [2720 kB]
Get:48 http://httpredir.debian.org/debian/ jessie/main grub2-common amd64 2.02~beta2-22+deb8u1 [505 kB]
Get:49 http://httpredir.debian.org/debian/ jessie/main ifenslave all 2.6 [15.6 kB]
Get:50 http://httpredir.debian.org/debian/ jessie/main libjpeg62-turbo amd64 1:1.3.1-12 [116 kB]
Get:51 http://httpredir.debian.org/debian/ jessie/main libsnmp-perl amd64 5.7.2.1+dfsg-1+deb8u1+b1 [1459 kB]
Get:52 http://httpredir.debian.org/debian/ jessie-backports/main lldpd amd64 0.9.5-1~bpo8+1 [197 kB]
Get:53 http://httpredir.debian.org/debian/ jessie/main lvm2 amd64 2.02.111-2.2+deb8u1 [713 kB]
Get:54 http://httpredir.debian.org/debian/ jessie/main openssh-sftp-server amd64 1:6.7p1-5+deb8u4 [37.9 kB]
Get:55 http://httpredir.debian.org/debian/ jessie/main openssh-server amd64 1:6.7p1-5+deb8u4 [331 kB]
Get:56 http://httpredir.debian.org/debian/ jessie/main perl-tk amd64 1:804.032-3+b3 [2031 kB]
Get:57 http://httpredir.debian.org/debian/ jessie/main tcpdump amd64 4.9.2-1~deb8u1 [415 kB]
Get:58 http://httpredir.debian.org/debian/ jessie/main tkmib all 5.7.2.1+dfsg-1+deb8u1 [1431 kB]
Get:59 http://httpredir.debian.org/debian/ jessie/main vlan amd64 1.9-3.2 [36.5 kB]
Get:60 http://httpredir.debian.org/debian/ jessie/main watchdog amd64 5.14-3 [85.0 kB]
Fetched 24.0 MB in 0s (0 B/s)
Sysroot is in /tmp/tmplcVIEq
Using copy:/mnt unstable main
Using http://deb.openswitch.net/jessie unstable main opx opx-non-free
Using http://httpredir.debian.org/debian jessie main
Using http://httpredir.debian.org/debian jessie-updates main
Using http://httpredir.debian.org/debian jessie-backports main
Get:1 http://deb.openswitch.net/jessie/ unstable/main opx-kernel-dell-3.16.0-4-amd64 amd64 3.16.43-2+deb8u2 [34.0 MB]
Get:2 http://httpredir.debian.org/debian/ jessie/main libuuid-perl amd64 0.05-1+b1 [10.4 kB]
Get:3 http://httpredir.debian.org/debian/ jessie/main linux-base all 3.5 [34.3 kB]
Get:4 http://httpredir.debian.org/debian/ jessie/main libklibc amd64 2.0.4-2 [51.7 kB]
Get:5 http://httpredir.debian.org/debian/ jessie/main klibc-utils amd64 2.0.4-2 [108 kB]
Get:6 http://httpredir.debian.org/debian/ jessie/main initramfs-tools all 0.120+deb8u3 [96.7 kB]
Fetched 34.3 MB in 0s (0 B/s)
Sysroot is in /tmp/tmplcVIEq
Using copy:/mnt unstable main
Using http://deb.openswitch.net/jessie unstable main opx opx-non-free
Using http://httpredir.debian.org/debian jessie main
Using http://httpredir.debian.org/debian jessie-updates main
Using http://httpredir.debian.org/debian jessie-backports main
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1395, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1345, in main
    rel_plan.add_packages()
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 946, in add_packages
    packer.fetch(names=deb_package_list)
  File "/opt/opx-build/scripts/opx_get_packages.py", line 475, in fetch
    from_user=False)
  File "/usr/lib/python2.7/dist-packages/apt/package.py", line 1149, in mark_install
    fixer.resolve(True)
opx_get_packages.OpxPackagesError: E:Unable to correct problems, you have held broken packages.
gms@debian:~/openswitch$

**Comment by theucke** [comment]
Ah, our unstable distribution of Jessie packages is broken at the moment. You can use 2.3.1 instead for our most recent Jessie release.

Yes, there is a Stretch blueprint, just use the file `opx-onie-installer/release_bp/OPX_dell_base_stretch.xml`.

**Comment by evwarner** [comment]
Yep, that worked!  And 2.3.1 was what was desired anyway.

Hey, thanks for the help.

--ericw
