### ISSUE TITLE
libopx-logging-dev issuse

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#50]
Some packages (like opx-common-utils) )depends on libopx-logging-dev, but it seems not built from the package "opx-logging".

Where can I get libopx-logging-dev ?
Thanks.

/etc/apt/sources.list.d/opx.list
--------------------------------
deb http://deb.openswitch.net/stretch unstable main opx opx-non-free
deb-src http://deb.openswitch.net/stretch unstable opx

[ 1017.593931] systemd-journald[2072]: Sent WATCHDOG=1 notification.
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Tempor'
W: Failed to fetch http://deb.openswitch.net/stretch/dists/unstable/InRelease  '
W: Some index files failed to download. They have been ignored, or old ones use.
I: user script /var/cache/pbuilder/build/cow.22133/tmp/hooks/D05update-sources d
 -> Attempting to satisfy build-dependencies
 -> Creating pbuilder-satisfydepends-dummy package
Package: pbuilder-satisfydepends-dummy
Version: 0.invalid.0
Architecture: arm64
Maintainer: Debian Pbuilder Team <pbuilder-maint@lists.alioth.debian.org>
Description: Dummy package to satisfy dependencies with aptitude - created by pr
 This package was created automatically by pbuilder to satisfy the
 build-dependencies of the package being currently built.
Depends: debhelper (>= 9), dh-autoreconf, libopx-logging-dev (>= 2.1.0), libxmlv
dpkg-deb: building package 'pbuilder-satisfydepends-dummy' in '/tmp/satisfydepe.
Selecting previously unselected package pbuilder-satisfydepends-dummy.
(Reading database ... 11570 files and directories currently installed.)
Preparing to unpack .../pbuilder-satisfydepends-dummy.deb ...
Unpacking pbuilder-satisfydepends-dummy (0.invalid.0) ...
dpkg: pbuilder-satisfydepends-dummy: dependency problems, but configuring anywa:
 pbuilder-satisfydepends-dummy depends on debhelper (>= 9); however:
  Package debhelper is not installed.
 pbuilder-satisfydepends-dummy depends on dh-autoreconf; however:
  Package dh-autoreconf is not installed.
 pbuilder-satisfydepends-dummy depends on libopx-logging-dev (>= 2.1.0); howeve:
  Package libopx-logging-dev is not installed.
 pbuilder-satisfydepends-dummy depends on libxml2-dev; however:
  Package libxml2-dev is not installed.

Setting up pbuilder-satisfydepends-dummy (0.invalid.0) ...
Reading package lists...
Building dependency tree...
Reading state information...
Initializing package states...
Writing extended state information...
Building tag database...
pbuilder-satisfydepends-dummy is already installed at the requested version (0.)
pbuilder-satisfydepends-dummy is already installed at the requested version (0.)
The following NEW packages will be installed:
  autoconf{a} automake{a} autopoint{a} autotools-dev{a} bsdmainutils{a} debhelp
The following packages are RECOMMENDED but will NOT be installed:
  curl libglib2.0-data libltdl-dev libmail-sendmail-perl lynx-cur shared-mime-i
0 packages upgraded, 34 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/36.7 MB of archives. After unpacking 165 MB will be used.
The following packages have unmet dependencies:
 pbuilder-satisfydepends-dummy : Depends: libopx-logging-dev (>= 2.1.0) which ie

Unable to resolve dependencies!  Giving up...
The following NEW packages will be installed:
  autoconf{a} automake{a} autopoint{a} autotools-dev{a} bsdmainutils{a} debhelp
The following packages are RECOMMENDED but will NOT be installed:
  curl libglib2.0-data libltdl-dev libmail-sendmail-perl lynx-cur shared-mime-i
0 packages upgraded, 34 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/36.7 MB of archives. After unpacking 165 MB will be used.
Abort.
E: pbuilder-satisfydepends failed.
I: Copying back the cached apt archive contents
I: unmounting /mnt/pool/stretch-arm64 filesystem
I: unmounting dev/ptmx filesystem
I: unmounting dev/pts filesystem
I: unmounting dev/shm filesystem
I: unmounting proc filesystem
I: unmounting sys filesystem
I: Cleaning COW directory
I: forking: rm -rf /var/cache/pbuilder/build/cow.22133
gbp:error: 'git-pbuilder' failed: it exited with 1

**Comment by atanu-mandal** [comment]
hi @jimmymagemtek , Can you check if you have opx-logging repo built successfully, essentially that should generate libopx-logging-dev. 
[https://github.com/open-switch/opx-logging/blob/cf50b5176314d38a2bb8aa9955f3060b45d24205/debian/control#L21](url)

Thanks,
-Atanu

**Comment by jimmymagemtek** [comment]
Hi Altanu,
I found the root cause might be that I can't get 
http://deb.debian.org/debian/dists/stretch/InRelease or 
http://deb.openswitch.net/stretch/dists/unstable/InRelease ',  since I am using arm64 platform.


Could you please provide the arm64-version InRelease files & the associated binaries ?

Thanks.

**Comment by jeff-yin** [comment]
Sorry, at this moment we only have support for x86.
