### ISSUE TITLE
Can't install opx-ip service

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#53]
Hi 
When installing opx-nas-linux_5.24.0_amd64.deb , I got the following error message:

root@NB03:/home/opx/pool/stretch-amd64/opx-nas-linux# dpkg -i opx-nas-linux_5.24.0_amd64.deb 
(Reading database ... 136751 files and directories currently installed.)
Preparing to unpack opx-nas-linux_5.24.0_amd64.deb ...
Unpacking opx-nas-linux (5.24.0) over (5.24.0) ...
Setting up opx-nas-linux (5.24.0) ...
Job for opx-ip.service failed because of unavailable resources or another system error.
See "systemctl status opx-ip.service" and "journalctl -xe" for details.
opx-ip.service couldn't start.
Job for opx-vrf.service failed because of unavailable resources or another system error.
See "systemctl status opx-vrf.service" and "journalctl -xe" for details.
opx-vrf.service couldn't start.
root@NB03:/home/opx/pool/stretch-amd64/opx-nas-linux# systemctl status opx-ip.service
● opx-ip.service - IP address handler
   Loaded: loaded (/lib/systemd/system/opx-ip.service; enabled; vendor preset: enabled)
   Active: failed (Result: resources)

Sep 17 04:03:48 NB03 systemd[1]: opx-ip.service: Failed to run 'start' task: No such file or directory
Sep 17 04:03:48 NB03 systemd[1]: Failed to start IP address handler.
Sep 17 04:03:48 NB03 systemd[1]: opx-ip.service: Unit entered failed state.
Sep 17 04:03:48 NB03 systemd[1]: opx-ip.service: Triggering OnFailure= dependencies.
Sep 17 04:03:48 NB03 systemd[1]: opx-ip.service: Failed to enqueue OnFailure= job: No such file or directory
Sep 17 04:03:48 NB03 systemd[1]: opx-ip.service: Failed with result 'resources'.
Sep 17 04:40:27 NB03 systemd[1]: opx-ip.service: Failed to load environment files: No such file or directory
Sep 17 04:40:27 NB03 systemd[1]: opx-ip.service: Failed to run 'start' task: No such file or directory
Sep 17 04:40:27 NB03 systemd[1]: Failed to start IP address handler.
Sep 17 04:40:27 NB03 systemd[1]: opx-ip.service: Failed with result 'resources'.
root@NB03:/home/opx/pool/stretch-amd64/opx-nas-linux# 

Any suggestion is appreciated.

**Comment by Tejaswi-Goel** [comment]
Which platform is this?

**Comment by jimmymagemtek** [comment]
Debian 9.5 in x86 (AMD64)

**Comment by atanu-mandal** [comment]
Is it an OPX supported platforms that you are trying on ? Also would like to understand your installation procedure, can you please shed some light on that ?

**Comment by jimmymagemtek** [comment]
This issue is closed because it is the same as issue #52.
