### ISSUE TITLE
Can't install all the deb files under opx-sdi-sys

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#54]
Hi Sir,
opx-platform-config-dell-s5148f depends on both libopx-sdi-sys1&  libopx-sdi-sys-vm1.
But, libopx-sdi-sys1 &  libopx-sdi-sys-vm1 conflict to each other.
Any suggestion is appreciated.

root@NB03:/home/opx/pool/stretch-amd64/opx-sdi-sys# dpkg -i libopx-sdi-sys-vm1_4.22.2_amd64.deb 
Selecting previously unselected package libopx-sdi-sys-vm1.
dpkg: regarding libopx-sdi-sys-vm1_4.22.2_amd64.deb containing libopx-sdi-sys-vm1:
 libopx-sdi-sys-vm1 conflicts with libopx-sdi
  libopx-sdi-sys1 provides libopx-sdi and is present and installed.

dpkg: error processing archive libopx-sdi-sys-vm1_4.22.2_amd64.deb (--install):
 conflicting packages - not installing libopx-sdi-sys-vm1
Errors were encountered while processing:
 libopx-sdi-sys-vm1_4.22.2_amd64.deb

**Comment by atanu-mandal** [comment]
Hi @jimmymagemtek , I assume you are trying on real S5148 . You do not require libopx-sdi-sys-vm1 as that is meant for VM platform. BTW opx-platform-config-dell-s5148f  shouldn't depend on  libopx-sdi-sys-vm1, it depends on only libopx-sdi-sys1.
