### ISSUE TITLE
how to run OPX services after the container is running

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#55]
Hi ,
Based on Intel Atom C2538 + Cavium CNX880XX, I built OPX docker image properly according to the guide on the web ,

opx-build/scripts/opx_run opx_build all

& try to run it. 

But I see no the virtual interfaces up - It seems no OPX service is up. Please check the log below.

My question is: how do I bring up OPX services when the container is run, so that I can see the virtual interfaces representing switch ports on Linux ? What OPX commands should I  issue ? Is there any document ?

In fact, I found that there is no OPX packages installed inside the docker image. 

It is confusing. Please advise. Thanks.

Thanks.
Jimmy

jimmy@NB03:/$ docker images
REPOSITORY          TAG                 IMAGE ID              CREATED                SIZE
opxhub/build        latest               2d13aa99f706       2 months ago        1.76GB
jimmy@NB03:/$ docker run -t -i opxhub/build:latest /bin/bash
root@576540c4f1c7:/mnt#
root@576540c4f1c7:/mnt# ls
root@576540c4f1c7:/mnt# cd ..
root@576540c4f1c7:/# ls
bin   entrypoint.sh  lib    mnt                 proc  sbin  tmp
boot  etc            lib64  opt                 root  srv   usr
dev   home           media  pbuilder_create.sh  run   sys   var
root@576540c4f1c7:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
8: eth0@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
root@576540c4f1c7:/#

**Comment by jghalam** [comment]
Hi Jimmy,
I'm confused as what you are reporting. Do you have build issues or running on unsupported platform issues?

If it is a build issue, please send us the build related logs. 

If you are having trouble running your compiled images on a supported platform (supported hardware or virtualbox based VM), please send us relevant information about your platform, and opx-show-version info so that we can help.
Thanks,
Joe

**Comment by jimmymagemtek** [comment]
Hi Joe,
I do have build issue. Could you provide the steps of how to build OPX packages & install them native on AS7512-32X.  It is also OK for me  if I can install them via apt-get  from Internet.

Thanks.

Jimmy

**Comment by theucke** [comment]
@jimmymagemtek 	Setting up the OPX apt repository is explained at [deb.openswitch.net](http://deb.openswitch.net/). You can then install `opx-dell-vm`.

**Comment by theucke** [comment]
There's been no update for almost two months, closing.
