### ISSUE TITLE
Can't build onie installer image

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-build#56]
Hi 
I strictly follow the guideline on OPX web site to build onie installer image.
After issuing 

# get source code
repo init -u https://github.com/open-switch/opx-manifest && repo sync

# build all open-source packages
opx-build/scripts/opx_run opx_build all

The final step is

# assemble installer
opx-build/scripts/opx_run opx_rel_pkgasm.py --dist unstable \
  -b opx-onie-installer/release_bp/OPX_dell_base.xml

But I got the error message as below, and using root privilege got the same result.
BTW, I am using a Debian 9.5 on Virtualbox on Win10, and installed docker before the compiling.

Please advise. Thanks.

Jimmy

jimmy@debian:/home/jimmy/opx$ opx-build/scripts/opx_run opx_rel_pkgasm.py --dist stable -b opx-onie-installer/release_bp/OPX_dell_base.xml
fetching http://archive.openswitch.net/rootfs/opx-rootfs_1.0.7-jessie_amd64.tar.gz ...
tar_in(self, /tmp/tmpYvg2jV, /)
tar_in(['fakeroot', '-i', '/tmp/tmpJQs1Tu', '-s', '/tmp/tmpJQs1Tu', 'tar', '-C', '/tmp/tmpHwKVVa/', '-x', '-f', '-', '-z', '--numeric-owner', '--preserve-permissions'])
update_rootfs(self)
do_chroot(self, /opt/opx-build/scripts/templates/do_apt_upgrade_sh)
do_chroot
['fakechroot', 'fakeroot', '-i', '/tmp/tmpJQs1Tu', '-s', '/tmp/tmpJQs1Tu', '/usr/sbin/chroot', '/tmp/tmpHwKVVa', '/do_apt_upgrade_sh']
/usr/sbin/chroot.fakechroot: line 105:    94 Segmentation fault      (core dumped) env -u FAKECHROOT_BASE_ORIG FAKECHROOT_CMD_ORIG= LD_LIBRARY_PATH="$fakechroot_chroot_paths" FAKECHROOT_BASE="$fakechroot_chroot_base" "$fakechroot_chroot_chroot" "${@:1:$(($fakechroot_chroot_n - 1))}" "${fakechroot_chroot_newroot#$FAKECHROOT_BASE_ORIG}" "${@:$(($fakechroot_chroot_n + 1))}"
Command '['fakechroot', 'fakeroot', '-i', '/tmp/tmpJQs1Tu', '-s', '/tmp/tmpJQs1Tu', '/usr/sbin/chroot', '/tmp/tmpHwKVVa', '/do_apt_upgrade_sh']' returned non-zero exit status 139
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1403, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1350, in main
    rel_plan.update_rootfs()
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 911, in update_rootfs
    self._root_obj.do_chroot(script_nm)
  File "/opt/opx-build/scripts/opx_rootfs.py", line 350, in do_chroot
    raise OpxrootfsError("Can't run script")
opx_rootfs.OpxrootfsError: Can't run script
jimmy@debian:~/opx$

**Comment by theucke** [comment]
Please try with the Stretch blueprint.
```bash
opx-build/scripts/opx_run opx_rel_pkgasm.py --dist stable -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml
```

**Comment by jeff-yin** [comment]
Closing for now; re-open if you are still facing issues.
