### ISSUE TITLE
Unable to create OPX installer with new Linux source packages

### ISSUE THREAD

**Issue by Tejaswi-Goel** [open-switch/opx-build#59]
Unable to create new OPX installer using new Linux source packages.

**_Steps followed:_**

1. created a stretch based docker container
2. linux source deb packages present in local dir 
 (linux-headers-4.9.110-custom-opx_4.9.110-custom-opx-2_amd64.deb
  linux-image-4.9.110-custom-opx_4.9.110-custom-opx-2_amd64.deb)
3. ran the command: **./opx-build/scripts/opx_rel_pkgasm.py -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml -n 0 -s test1-opx -v 9**

It was expected that the script **opx_rel_pkgasm.py** will pick up the new Linux source packages in the local directory to create the installer but that did not happen. 
Please let me know how to create a new OPX onie installer with new Linux packages. 

Thanks,
Tejaswi

**Comment by theucke** [comment]
The packages you downloaded have the package names `linux-*-4.9.110-custom-opx`. The blueprint only lists [linux-image-4.9.0-6-amd64](https://github.com/open-switch/opx-onie-installer/blob/master/release_bp/vendor/dell/opx_core_stretch.xml#L15). You'll need to change the package name in the blueprint for it to be picked up.

**Comment by Tejaswi-Goel** [comment]
Thanks, will try it out.
