### ISSUE TITLE
Failed to build an installer file for OPX 3.2.0

### ISSUE THREAD

**Issue by msarig** [open-switch/opx-build#73]
I'm trying to build an installer file as explained in [https://github.com/open-switch/opx-build/blob/master/README.md#installation](https://github.com/open-switch/opx-build/blob/master/README.md#installation). The error occurs during the command:
```
opx-build/scripts/opx_run opx_rel_pkgasm.py --dist stable -b opx-onie-installer/release_bp/OPX_dell_base_stretch.xml
```
The final error message is:
```
Traceback (most recent call last):
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1401, in <module>
    sys.exit(main())
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 1351, in main
    rel_plan.add_packages()
  File "/opt/opx-build/scripts/opx_rel_pkgasm.py", line 944, in add_packages
    packer.fetch(names=deb_package_list)
  File "/opt/opx-build/scripts/opx_get_packages.py", line 476, in fetch
    from_user=False)
  File "/usr/lib/python2.7/dist-packages/apt/package.py", line 1309, in mark_install
    fixer.resolve(True)
opx_get_packages.OpxPackagesError: E:Unable to correct problems, you have held broken packages.
```
In the output I notice an error related to gpg:
```
sudo: unable to resolve host 025368b40958: Connection timed out
Executing: /tmp/apt-key-gpghome.kmZylICkhT/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD5073F1
gpg: keyserver receive failed: Server indicated a failure
```
The host machine has full Internet connectivity. 
[opx-build-installer.txt](https://github.com/open-switch/opx-build/files/3681108/opx-build-installer.txt)
The full command output is attached.
I'm running Debian 9.11 amd64 and Docker 19.03.2.

Any idea what's going wrong? Thanks.

**Comment by jeff-yin** [comment]
@mapatel7 can you look into this?

**Comment by jeff-yin** [comment]
@msarig I know you said your host machine has full Internet connectivity, but it looks like it's failing while trying to connect to the Ubuntu keyserver, at this step:
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD5073F1`

You may need to troubleshoot why the above command doesn't work on your host. Perhaps the hkp connections are being restricted? Destination port tcp|udp/11371.

https://github.com/open-switch/opx-build/search?q=AD5073F1&unscoped_q=AD5073F1

**Comment by msarig** [comment]
Hi Jeff.
Thanks for looking into this.
When I run the command manually, it succeeds:

```
root@buildhost:~# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD5073F1
Executing: /tmp/apt-key-gpghome.PoaIU6oG7p/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD5073F1
gpg: key 5EF20F36AD5073F1: "OpenSwitch <opx@openswitch.net>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```
Also `tcpdump` shows approx 20 packets in the background transferred between my host and `keyserver.ubuntu.com`

**Comment by mapatel7** [comment]
Hi @msarig ,

Does this by any chance happen in a fresh workspace? By a new workspace, i mean clone the both repos: 'opx-build' and 'opx-onie-installer' and run this command again. Does it still show you the same error?

Let me know.

**Comment by msarig** [comment]
Hi @mapatel7 ,
Even in a fresh workspace the command produces the same error message.

**Comment by mapatel7** [comment]
Hi @msarig ,

Run the 'opx_run' script without any parameter, then inside the container do the following steps:

sudo apt-get update
sudo apt-get install -y curl dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD5073F1

Do you see any error while doing this?

**Comment by msarig** [comment]
Hi @mapatel7 
No errors while running the commands:
```
root@buildhost:/usr/src/opx-build/scripts# ./opx_run
root@a4c6a7f7f86e:/mnt# sudo apt-get update
Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:2 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Hit:4 http://deb.openswitch.net/stretch unstable InRelease
Get:5 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages [499 kB]
Hit:6 http://cdn-fastly.deb.debian.org/debian stretch Release
Fetched 684 kB in 0s (747 kB/s)
Reading package lists... Done
root@a4c6a7f7f86e:/mnt# sudo apt-get install -y curl dirmngr
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u9).
dirmngr is already the newest version (2.1.18-8~deb9u4).
dirmngr set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@a4c6a7f7f86e:/mnt# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD5073F1
Executing: /tmp/apt-key-gpghome.GxUPBZQAA5/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD5073F1
gpg: key 5EF20F36AD5073F1: "OpenSwitch <opx@openswitch.net>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by msarig** [comment]
Sure, here you are: [opx_build_installer.txt](https://github.com/open-switch/opx-build/files/3701487/opx_build_installer.txt)
The `do_apt_upgrade_sh` script is running inside a chroot environment, right? How can I reproduce this manually?

**Comment by msarig** [comment]
Note: I started a wireshark session in the background. When the script reaches this line:
```
Executing: /tmp/apt-key-gpghome.vVMs30iAi4/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD5073F1
```
there are no packets visible to the keyserver. When I run the `apt-key` command manually in the docker container, Wireshark shows 15 packets containing the key transfer.
I hope this information is helpful.

**Comment by mapatel7** [comment]
Hi @msarig ,

At this moment, i feel that this is a DNS issue for you. Can you share what is in your /etc/resolv.conf'?

**Comment by msarig** [comment]
Hi @mapatel7 ,
I'm using a local DNS server which is running `dnsmasq`. My DNS settings in `/etc/resolv.conf` is:
```
domain openswitch.lab
search openswitch.lab
nameserver 10.5.1.253
```
Since you mentioned a possible DNS issue, I changed the DNS settings to use the Google DNS server at 8.8.8.8, but the result is the same.

**Comment by alimodarresi** [comment]
Hi  @msarig 
did you resolve this problem?
I am also trying to build OPX 3.1.0 or 3.1.0. But while trying to create onie installer i am getting the same error. Can you help me fix it?

**Comment by msarig** [comment]
Hi @alimodarresi 
sorry, no progress since.
I wasn't able to fix it myself, that' s why I reach out for help here...

**Comment by alimodarresi** [comment]
Thanks @msarig  .
@jeff-yin can you help us?

**Comment by alimodarresi** [comment]
Hi @mapatel7  
I am getting the same error building OPX 3.0.0 , 3.1.0 and 3.2.0 stable versions. Can you help me, please?

**Comment by mikelazar** [comment]
We'll take another look into into this. There may still be something strange with DNS or accessing a specific web server.

**Comment by gunasekaran-t** [comment]
@msarig can you try with `--dist 3.2.0` or `--dist unstable` and see if the issue still occurs.

**Comment by alimodarresi** [comment]
Hi @gunasekaran-t  .
This worked for me. Thank you.

**Comment by mikelazar** [comment]
Assuming that this is fixed. Please reopen (or open another issue) if there are still problems.
