### ISSUE TITLE
Installing OPX

### ISSUE THREAD

**Issue by alimodarresi** [open-switch/opx-build#76]
Hi.
I have read the instruction for installing OPX on DELL hardware. Can someone give me more detailes?
Like which directories do i have to use for installation?

thanks

**Comment by jghalam** [comment]
Could you please provide more information about the hardware platform and how you’re installing OPX? Are you using ONIE to perform installation? What does your setup look like?

Thanks

**Comment by alimodarresi** [comment]
> Could you please provide more information about the hardware platform and how you’re installing OPX? Are you using ONIE to perform installation? What does your setup look like? Thanks
> […](#)
> On Jan 19, 2020, at 3:30 AM, alimodarresi ***@***.***> wrote: ﻿ Hi. I have read the instruction for installing OPX on DELL hardware. Can someone give me more detailes? Like which directories do i have to use for installation? thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I am trying to install OPX on S4048-ON and I am using ONIE.
I have built OPX 3.1.0 and now I have the binary. I didn't run the ./docker_build.sh because I dont know what it will do. If you know I will appreciate it if you tell me. I was following instruction from link below.
https://github.com/open-switch/opx-build/

**Comment by gunasekaran-t** [comment]
Hi, 

If you have the installer image you can follow ONIE install steps https://opencomputeproject.github.io/onie/cli/index.html#onie-nos-install 
or use ONIE image discovery option https://opencomputeproject.github.io/onie/design-spec/discovery.html

Thanks

**Comment by alimodarresi** [comment]
hi @gunasekaran-t .
I have some problems with building kernel source for OPX. Can you help me please?

**Comment by gunasekaran-t** [comment]
@alimodarresi yes, please provide the details. I will try if I can help.

**Comment by alimodarresi** [comment]
Thanks @gunasekaran-t .
Which kernel source do I have to build and which toolchains do I have to use?
And how can I build OPX on top of that?

**Comment by gunasekaran-t** [comment]
@alimodarresi , please refer https://github.com/open-switch/opx-linux-config

**Comment by mikelazar** [comment]
@alimodarresi  Please reopen if you have any other questions - or if this still does not work. Thank you.
